### ISSUE TITLE
Problem with editing Mii interaction patterns

### ISSUE THREAD

**Issue by Kuakabek** [Brionjv/Tomodachi-Life-Save-Editor#100]
Can someone please explain how to edit the interaction patterns properly so it shows up in game? I have been trying to edit an interaction for one of my Miis (who is married) to think about having a baby. Every time I select the interaction pattern "I've been thinking about having a child with {Mii}" it tells me to select a spouse. But, it doesn't give me the option to select a spouse even though she is already married with a spouse. It has a target option and I have both tried changing it to my spouse's mii name and just keeping it on mine. I save multiple times on the save editor on both save things (aka the option on the thing and at the top). I open my game and nothing, all I can think of is using the expression file somehow. But, I don't know how to even use it in the first place. I use the citra emulator and my save file is USA btw!

**Comment by Brionjv** [comment]
Hi, you need to use a recent save file, save in your game, extract your save file edit and restore. Interactions will show

**Comment by Kuakabek** [comment]
I use an emulator and my save file doesn't need to be extracted. It is recent and whenever I do the target thing it doesn't work at all when I have the interaction for both.

**Comment by Kuakabek** [comment]
nvm it worked! I guess I messed up some steps tysm

**Comment by Loveep** [comment]
now,in my case,i dunno how to restore,edit or extract,because i only 10,can you give me a tutorial video,Brionjv?

**Comment by Brionjv** [comment]
You need a hacked 3ds, extract and restore your save file with checkpoint homebrew
