### ISSUE TITLE
Internet connected but an error has occured + Cursor not working

### ISSUE THREAD

**Issue by Kagura101** [Brionjv/Tomodachi-Life-Save-Editor#101]
So it's asking me to connect to the internet for updates but I am connected to the internet? 
![image](https://user-images.githubusercontent.com/95944842/145655241-12e822a9-ecc2-40bf-8d4f-eca58a2f914a.png)
Am i missing something? I have the latest release of Tomodachi Life EX 1.0.2

Also whenever I try to select Extras and such, it won't let me select, could you please change the cursor situation?

**Comment by Brionjv** [comment]
`So it's asking me to connect to the internet for updates but I am connected to the internet?`

you can close save editor and retry, if you have always this message, you can check "unactive check updates" in settings. You have an older version of Windows it's can cause some trouble. I'lll see if I can fix that later.

`Am i missing something? I have the latest release of Tomodachi Life EX 1.0.2`

`Also whenever I try to select Extras and such, it won't let me select, could you please change the cursor situation?`

In EX version only relationships are editable

**Comment by Kagura101** [comment]
`you can close save editor and retry, if you have always this message, you can check "unactive check updates" in settings. You have an older version of Windows it's can cause some trouble. I'lll see if I can fix that later.`

well checking "Unactive check updates" stopped the message from appering so maybe it has something to do with Windows 7? either way, i hope you can fix this.

`In EX version only relationships are editable, to edit other features use version 4.0.1`

that's kind of a bummer, i was kinda hoping to edit Mii's interactions since EX version is the only version that's able to do that for ya.

**Comment by Brionjv** [comment]
Other features will be added later, I try to rewrite all features ti fix all issues

**Comment by Brionjv** [comment]
should be fixed now
