### ISSUE TITLE
I can't open the save file.

### ISSUE THREAD

**Issue by KatTheCatt** [Brionjv/Tomodachi-Life-Save-Editor#103]
Hello!
I have the save data on my computer, but when I try to open it with Tomodachi Life Save Editor, then it says I need to contact the owner of the file to open it? I'm confused, and I really want to use this!
I have both JKSM and Checkpoint versions saved, both don't work.

**Comment by Brionjv** [comment]
Hello,
can you send a picture of your error, please ? if you have this : 

![issue section](https://user-images.githubusercontent.com/22226393/146640057-110485ab-9901-4cd2-8baa-703e44fc26c7.png)

it's only issues in this version, you can back to menu
