### ISSUE TITLE
Save File keeps on corrupting.

### ISSUE THREAD

**Issue by iFranYT** [Brionjv/Tomodachi-Life-Save-Editor#104]
So I'm trying to edit this file and it keeps saying it's corrupted.
Can someone help?

[Download](https://drive.google.com/file/d/11BiDTqCkNTiY-N8kk92ZkC_67vQ1SUZR/view?usp=sharing)

**Comment by Brionjv** [comment]
![two spouses](https://user-images.githubusercontent.com/22226393/146639629-bfd655f0-6742-4874-a2b2-4eebf0548f85.png)

save is corrupted because Clara have two spouses
