### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Larureen** [Brionjv/Tomodachi-Life-Save-Editor#11]
Hello, my question is when do you release the new version? And how can I choose which Miis marries?
Thank You 👍 😆

**Comment by Brionjv** [comment]
Hello, I don't know when I release a new version sorry, I need some time to add features. For now you can't choose which Miis marries. I'll add "choose which Miis marries" to idea for update. If I found something about it, he will be added

**Comment by Larureen** [comment]
ok thank you, do you think the new update will come this mounth?

**Comment by Brionjv** [comment]
for now I don't know, sorry
