### ISSUE TITLE
all options in ex labled with 🚫

### ISSUE THREAD

**Issue by bssiajer** [Brionjv/Tomodachi-Life-Save-Editor#110]
Everytime I hover my mouse over an option that isn't settings, my mouse displays a 🚫 and won't let me click on it. I don't know if this bug or not.
Using physical 1.2 copy and US version.

**Comment by GenerationX-sudo** [comment]
having the same problem, have no idea what to do. did you manage to find a way to fix it?

**Comment by bssiajer** [comment]
I still haven't found a way to fix it yet.

**Comment by Brionjv** [comment]
only "Mii edition" and "settings" are available in EX version

**Comment by spudpiggy** [comment]
What's the point of it then?

**Comment by Brionjv** [comment]
nothing for now
