### ISSUE TITLE
Save file corrupted but I can't really find the source of the corruption.

### ISSUE THREAD

**Issue by edfrick** [Brionjv/Tomodachi-Life-Save-Editor#111]
I was pretty sure I had messed something up with the relationships but I cannot seem to find what causes the issue.
[savedataArc.txt](https://github.com/Brionjv/Tomodachi-Life-Save-Editor/files/8238871/savedataArc.txt)

**Comment by Brionjv** [comment]
I reset relationships and save file still corrupted, is not relationships, are you used an other features ?

**Comment by edfrick** [comment]
I remember I tried unlocking some buildings of the island that weren't unlocked yet, but I believe that's all I did and when reverted the file was still corrupted so I'm currently at a loss.

**Comment by Brionjv** [comment]
you can restore an older save file, check backup folder in save editor location. I try to found why save file is corrupted

**Comment by Brionjv** [comment]
I try, I work on a feature to export Miis but I need some times

**Comment by edfrick** [comment]
You're fine, I appreciate the help regardless.

**Comment by Brionjv** [comment]
what is your region game ?

**Comment by edfrick** [comment]
USA!

**Comment by Brionjv** [comment]
ok, I'll try to transfert your Miis in a new save file

**Comment by edfrick** [comment]
Thank you! I greatly appreciate it

**Comment by Brionjv** [comment]
I successfully transfert your Miis, I try to restore relationships and other things

**Comment by edfrick** [comment]
Dude you are actually incredible thank you so much

**Comment by Brionjv** [comment]
[savedataArc.txt](https://github.com/Brionjv/Tomodachi-Life-Save-Editor/files/8251647/savedataArc.txt)

here your save file with all things except relationships, relationships cause save file corruption.

**Comment by edfrick** [comment]
Thanks man! This is amazing! If you have an update on the relationships ill take it but this is for sure better then nothing, I cannot thank you enough

**Comment by Brionjv** [comment]
no problem, I try to check relationships

**Comment by edfrick** [comment]
Keep me posted!

**Comment by Brionjv** [comment]
I don't know why relationships corrupt save file sorry, it's weird

**Comment by edfrick** [comment]
I made an actual backup this time around and was able to make my character date someone with no issues, this is pretty strange.

**Comment by Brionjv** [comment]
This is not relationships, some value has been edited on a empty Mii place, probably interaction

**Comment by Brionjv** [comment]
It's not relationships, it's some unknow values

here your save file with all things restored : 

[savedataArc.txt](https://github.com/Brionjv/Tomodachi-Life-Save-Editor/files/8252457/savedataArc.txt)

**Comment by edfrick** [comment]
Dude thank you so much, I actually thought the save file was completely gone, ur amazing.

**Comment by Brionjv** [comment]
no problem, I'll add something to fix that on the editor
