### ISSUE TITLE
cant force my miis to have a child

### ISSUE THREAD

**Issue by MysticMytisc** [Brionjv/Tomodachi-Life-Save-Editor#112]
when i use the "ive been thinking about having a baby with {mii}" interaction or "{mii} and i had a baby" it doesnt work.
i met all the criteria in the red bubbles, (theyre both married and i selected a spouse mii) it still doesnt work
im using citra if that means anything

**Comment by Brionjv** [comment]
did you allow birth of babies in tomodachi life settings ?

**Comment by SummerSkies** [comment]
Editing the save file automatically sets the baby settings to "off".

**Comment by LitPotato2895** [comment]
> when i use the "ive been thinking about having a baby with {mii}" interaction or "{mii} and i had a baby" it doesnt work. i met all the criteria in the red bubbles, (theyre both married and i selected a spouse mii) it still doesnt work im using citra if that means anything

Im having the same issue (not on citra tho, on a regular 3DS) , i respected all conditions and i have babies turned on so im not sure what the issue is :( did you ever fix it or no?

**Comment by LitPotato2895** [comment]
> Editing the save file automatically sets the baby settings to "off".

it doesnt do that on my game and it still doesnt work

**Comment by Brionjv** [comment]
In previous version, Time penality feature turn off birth of babies. I update this in EX version
