### ISSUE TITLE
Save file is corrupted and i dont know why 

### ISSUE THREAD

**Issue by sayoganyu** [Brionjv/Tomodachi-Life-Save-Editor#113]
heres the save file, if someone can please find the issue, thanks.
[savedataArc.txt](https://github.com/Brionjv/Tomodachi-Life-Save-Editor/files/8311156/savedataArc.txt)

**Comment by Brionjv** [comment]
Liepa have 2 best friends, you need delete one

**Comment by sayoganyu** [comment]
alright thanks!
