### ISSUE TITLE
Can't make a have a baby problem

### ISSUE THREAD

**Issue by Hollywoodbro12** [Brionjv/Tomodachi-Life-Save-Editor#114]
I tried to force a couple to have a baby with the editor but nothing happens in-game with either mii (I tried it on both and they're also soulmates) and I know for sure that babies are on since I've had a natural one on the save before (I'm using citra btw)

**Comment by Hollywoodbro12** [comment]
...wait just checked they're off for some reason idk why

**Comment by SummerSkies** [comment]
I've had the same problem and have realized that editing the save file automatically sets baby settings to "off". Turning it back on and saving this change makes no difference.

**Comment by Brionjv** [comment]
Time penality feature has been update, you need to used version EX to fix this
