### ISSUE TITLE
Corrupt after Altering Food Preferences

### ISSUE THREAD

**Issue by Hiraeth-Fern** [Brionjv/Tomodachi-Life-Save-Editor#115]
While everything else about the save is wonderful, whenever I try and edit the favorite/hated foods, my data is *always* corrupted. If I'm the idiot, please let me know - thank you!

**Comment by Brionjv** [comment]
try with an other value if your food is not listed

**Comment by Hiraeth-Fern** [comment]
I worked it out - you need to first give a mii something to eat, then you're able to edit it. Thanks!

**Comment by Hiraeth-Fern** [comment]
**Note to Others**
If this is an issue for your save, be sure you've given a mii something to eat first before altering people's food choices! 😊
