### ISSUE TITLE
editing mii relationships issue

### ISSUE THREAD

**Issue by LukaPeluca** [Brionjv/Tomodachi-Life-Save-Editor#116]
when I try to edit mii relationships the program says that it "failed to read friend list of this mii" and when I go to the friend list all the miis are set to "unknow" and I'm afraid to hit the save button because I'm trying to force some miis to date and i'm afraid the mii will lose all their friendships if I hit save after making them together with the mii that i want them to date

**Comment by Brionjv** [comment]
Did you used last version ?

**Comment by Galorlx** [comment]
> Did you used last version ?

I have a problem related with it being I get corrupted save data trying to do the same thing

**Comment by Brionjv** [comment]
if you have "failed to read friend list of this mii", your save file is not opened in save editor.  Can you send your save file to see what goes wrong ?

**Comment by Galorlx** [comment]
> if you have "failed to read friend list of this mii", your save file is not opened in save editor. Can you send your save file to see what goes wrong ?

I’ll send that over in a second but no I don’t get the friend list error
