### ISSUE TITLE
Cannot edit items, extra or concert

### ISSUE THREAD

**Issue by poicyss** [Brionjv/Tomodachi-Life-Save-Editor#122]
![image](https://user-images.githubusercontent.com/106847040/171961560-59288fbc-52a5-48bf-b31b-c962ac0426e9.png)
For some reason these things are greyed out, and no matter what I just cannot access them. I have a physical copy and tried backing up my files through both checkpoint and JKSM, both giving me the same result. Everything that I do have access to (Mii edit, etc) works just fine.

**Comment by Brionjv** [comment]
just use EX version included

**Comment by poicyss** [comment]
The EX version doesn't save updated data. I press the save button and it gives me a "tomodachi life" box with no buttons.
![image](https://user-images.githubusercontent.com/106847040/173267315-9928e1f4-5473-4899-ac5e-860a81ed5bc0.png)

**Comment by Brionjv** [comment]
go in settings and change language and retry

**Comment by poicyss** [comment]
Worked! Thank you :)

**Comment by vonnieboney227** [comment]
What do I do when the island address is corrupted and all of my data is erased because the corruption?

**Comment by vonnieboney227** [comment]
here is why it won't work for me:
the Island address is corrupted
nothing is changed when I load the game
the items icon is blured gray and cannot be accessed
