### ISSUE TITLE
I can't open a save file.

### ISSUE THREAD

**Issue by FlorasGithub** [Brionjv/Tomodachi-Life-Save-Editor#124]
When I open a savedataArc file it prompts me with the Europe or USA save file thing, I click on USA and my file doesn't load!

![YUJ](https://user-images.githubusercontent.com/106929149/172067010-d2036ebb-c6ad-4582-9eeb-7c02318e7312.PNG)

**Comment by Brionjv** [comment]
Change your save file location and retry. Save editor is probably block by your firewall or antivirus. Try with your save file in Download folder

**Comment by FlorasGithub** [comment]
That didn't work

**Comment by Brionjv** [comment]
I don't know how to help you more, is not come from save editor. I'll try to found but for now I don't know
