### ISSUE TITLE
[Development] PackageIO 0.1.7.0 can't write byte or uint8

### ISSUE THREAD

**Issue by Brionjv** [Brionjv/Tomodachi-Life-Save-Editor#13]
Programming of Tomodachi Life Save Editor is stuck : 
I looking for an alternative to write by byte or by unsigned integer 8.
Updating PackageIO to highter versions causes an issue to read and write unicode in an specific offset

**Comment by colt05-usr** [comment]
I'm going to try to fix this.

**Comment by Brionjv** [comment]
I think I found an alternative : 
`Dim fs As New FileStream(filepath, FileMode.Open, FileAccess.ReadWrite, FileShare.ReadWrite)
            fs.Position = Miifr1
            fs.WriteByte(NumericUpDown59.Value)`
-> written the relationship of the selected Mii with a Mii in friend list

it seem to work, but i need more test. If you have found a better code tell me, thanks 👍
