### ISSUE TITLE
cannot open interaction on EX

### ISSUE THREAD

**Issue by Kazutoes** [Brionjv/Tomodachi-Life-Save-Editor#130]
![wheee](https://user-images.githubusercontent.com/67227866/175567968-2ac6a649-0b6e-4bf2-b85c-280ec3c49043.PNG)
![ha](https://user-images.githubusercontent.com/67227866/175567970-4a2e1cee-3ae4-4a86-ad3c-b939e5e0c113.PNG)

**Comment by Brionjv** [comment]
is not available for now, interaction is available in version 4.0.4
