### ISSUE TITLE
corrupted when editing relationship

### ISSUE THREAD

**Issue by atlasbotch** [Brionjv/Tomodachi-Life-Save-Editor#131]
so when i edit a relationship with a mii so they can be in love it just corrupts my save file, i tried to do the thing where you give the mii 3 favorite foods but it didnt work. :/

**Comment by Brionjv** [comment]
give mii favorite foods is only if mii edit is used in version 4.0.4 (relationships in 4.0.4 has been disabled)
For relationships check if both Mii don't have duplicate special someone (duplicate special someone or best friend wil be set in red)
