### ISSUE TITLE
.mii/.tlmii is not the proper extension

### ISSUE THREAD

**Issue by HEYimHeroic** [Brionjv/Tomodachi-Life-Save-Editor#136]
i noticed that the editor has support for "importing .mii" or ".tlmii", however after taking a closer look, it seems like this extension is actually referring to the .cfsd/.ffsd extensions. .mii is not used for the Wii U/3DS Mii data files, and instead is named .cfsd for 3DS and .ffsd for Wii U (though, both should be allowed, as they're the same format internally, just with multiple official names). .mii has only ever been used in Mario Golf: Super Rush to refer to the charinfo format, only used on the Switch in games. the .tlmii extension is not necessary as it seems to be the exact same as .cfsd/.ffsd files. an example of two .cfsd files and one .ffsd file can be found here:

example of .cfsd from Pilotwings Resort/example of what a player's .cfsd may look like: https://github.com/HEYimHeroic/MiiDataFiles/blob/main/Mii%20data%20files/3DS/Pilotwings%20Resort/OfficeLady/OfficeLady.cfsd

example of the blank .cfsd file Tomodachi Life uses for empty Mii slots: https://github.com/HEYimHeroic/MiiDataFiles/blob/main/Mii%20data%20files/3DS/Tomodachi%20Life/blank.cfsd

example of .ffsd, to show it is functionally almost the same as .cfsd files: https://github.com/HEYimHeroic/MiiDataFiles/blob/main/Mii%20data%20files/Wii%20U/WaraWara%20Plaza/mii36internetbrowser04/mii36internetbrowser04.ffsd

edit: i realized i should also include an example of the .mii format, only used twice in Mario Golf: Super Rush. this format can't be supported as it's used by the Switch, not the 3DS, but it's still worth sharing: https://github.com/HEYimHeroic/MiiDataFiles/blob/main/Mii%20data%20files/Switch/Mario%20Golf%20-%20Super%20Rush/pr_f/pr_woman.charinfo
(the file extension here is renamed to be .charinfo just for consistency, but in the game files it is called .mii)

**Comment by Brionjv** [comment]
Hi,
I'll update save editor following these informations .tlmii file is used by an abandoned feature, I had keep him on save editor because I had some doubts on Mii format

thank you for these informations
