### ISSUE TITLE
always corrupts whenever i try to get all clothing

### ISSUE THREAD

**Issue by tilxtz** [Brionjv/Tomodachi-Life-Save-Editor#140]
whenever i try to like. get all houses, clothing, streetpass stuff anything it just always corrupts

**Comment by Brionjv** [comment]
did you used last version, what is your game region ?

**Comment by tilxtz** [comment]
turns out i was using the wrong region.. heh, my bad! keep up the good work! so sorry for wasting your time!

**Comment by Brionjv** [comment]
no problem
