### ISSUE TITLE
Mii inventory and Appearance blocked out?

### ISSUE THREAD

**Issue by sluggort** [Brionjv/Tomodachi-Life-Save-Editor#147]
When I hover over those 2 in the Mii edition section, it shows the 🚫 cursor and I can't click on them. I use the USA version.

**Comment by Brionjv** [comment]
is not available for now

**Comment by sluggort** [comment]
Thanks, and that's alright! I can just give them items myself.

**Comment by Brionjv** [comment]
Mii inventory section is now available
