### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by the2thomasklu8** [Brionjv/Tomodachi-Life-Save-Editor#150]
Whenever I try to open something in the newest versions, it just gives me the following error:

Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Could nod load file or assembly *PackageIO, Version=0.1.7.0. Culture-neutral. PublicKeyToken=null* or one iof its dependencies. The system cannot find the file specified.

I have attached a file with the details
[Error Report.txt](https://github.com/Brionjv/Tomodachi-Life-Save-Editor/files/9351718/Error.Report.txt)
.

**Comment by Brionjv** [comment]
Hi, you need to have PackageIO.dll to same folder as save editor
