### ISSUE TITLE
New Interaction: 18A, 189 - Item Lost

### ISSUE THREAD

**Issue by Hazuki-san** [Brionjv/Tomodachi-Life-Save-Editor#151]
![image](https://user-images.githubusercontent.com/27200811/186918653-1c86aadb-e148-49f4-9dee-74cbf15bd330.png)
![image](https://user-images.githubusercontent.com/27200811/186918835-18bd7c8b-96db-44bc-87a5-dfd120f93531.png)

18A - Found Item
189 - Waiting for item to be found

Target 1: Mii ID
Target 2: Probably Item ID

Transcript (EUR):
18A -
Mii: I found this!
Mii: Hey! It has {Mii} written on the back...
Mii: Can you give it back to {Mii}?

189 -
Mii: What?! You found it? Thank you so much!
Mii: So, {Mii} found it?
Mii: I'm so relieved! This means so much to me. Thanks!

**Comment by Brionjv** [comment]
thanks, I'll add them when I have time

**Comment by ctkemp-collab** [comment]
how do i get to this part of the page I'm stuck
