### ISSUE TITLE
version 5.0.8 STILL corrupts save data when i edit favorite foods

### ISSUE THREAD

**Issue by dreamycarnival** [Brionjv/Tomodachi-Life-Save-Editor#152]
even though this update was supposed to fix the problem. changing favorite foods STILL murders the save data.

there also seems to be a bug that switches all non-look a like mii's super all time favorite to ice cream cone?

if it helps i use JKSV to store save data.

**Comment by Hazuki-san** [comment]
Can confirm, now every Mii all time fav are now ice cream cone

**Comment by Brionjv** [comment]
what is your save file region ?

**Comment by dreamycarnival** [comment]
US

**Comment by Brionjv** [comment]
ok, I'll see

**Comment by Hazuki-san** [comment]
@Brionjv maybe use the same code as V4? That version wasn't broken.

**Comment by Brionjv** [comment]
I use it but something goes wrong, for now I don't why

**Comment by Brionjv** [comment]
see issues / legends in save editor, if other things goes wrong open an other issue
