### ISSUE TITLE
All Miis' super all-time favorite besides Mii 1 default to Ice Cream Cone

### ISSUE THREAD

**Issue by OrangeTheYoshi** [Brionjv/Tomodachi-Life-Save-Editor#153]
When you put in a save file, every mii besides Mii 1 will have their super all-time favorite default to Ice Cream Cone, even when their super all-time favorite isn't that.
Images: https://cdn.discordapp.com/attachments/646909353529573436/1013310246644625448/20220827_235148.jpg?size=4096 (in-game), https://cdn.discordapp.com/attachments/646909353529573436/1013310340903227432/unknown.png?size=4096 (editor)

Mii 1: https://cdn.discordapp.com/attachments/646909353529573436/1013310784236961833/20220827_235432.jpg?size=4096 (in-game), https://cdn.discordapp.com/attachments/646909353529573436/1013310755396915240/unknown.png?size=4096 (editor)

Perfect example of the bug: https://cdn.discordapp.com/attachments/646909353529573436/1013311401114222652/unknown.png?size=4096

**Comment by Brionjv** [comment]
I'll see

**Comment by Brionjv** [comment]
see issues / legends in save editor, if other things goes wrong open an other issue

**Comment by SaimonWoidig** [comment]
I have encountered this issue aswell. But changing to another food didn't help sadly. See https://github.com/Brionjv/Tomodachi-Life-Save-Editor/issues/246#issuecomment-2737930914. On latest version of the editor.
If this project is still active, I can create a new issue and provide whatever is necessary.
