### ISSUE TITLE
Add to Universal Updater?

### ISSUE THREAD

**Issue by Randomeder** [Brionjv/Tomodachi-Life-Save-Editor#155]
Would be nice to have Tomodachi Life and Miitopia save editor on the Universal Updater. (https://db.universal-team.net/)

**Comment by Brionjv** [comment]
Hi, 
save editors are windows applications, not a 3ds homebrew
So I think is not necessary

**Comment by Randomeder** [comment]
Oh, right. XD I didnt see that! Thanks for responding though!
