### ISSUE TITLE
Missing House(s)

### ISSUE THREAD

**Issue by SuperLuigiGlitchy3** [Brionjv/Tomodachi-Life-Save-Editor#205]
Hello! I edited my save file to make 2 married couples but, when i imported my data and launched the game, there's only one married couple's house and when both couples are in the house, only one of the four persons appears. how can i fix this?

**Comment by Brionjv** [comment]
Hi, you need to edit Mii houses, Married Miis need to have same unique Mii house

**Comment by DrBlakk** [comment]
> Hi, you need to edit Mii houses, Married Miis need to have same unique Mii house

how and where
