### ISSUE TITLE
Save data corrupting when changing Mii friends

### ISSUE THREAD

**Issue by Zeezers** [Brionjv/Tomodachi-Life-Save-Editor#21]
Yeah, pretty self-explanatory. I try to change my Mii's friends in the save editor, but no matter what I do the save keeps getting corrupted after I save it. So this editor should be updated to better edit the savedataArc.txt file without corrupting it.

**Comment by Brionjv** [comment]
Hi,
I'll try to see what goes wrong, can you send your corrupted save file please ?

**Comment by Zeezers** [comment]
[savedataArc.txt](https://github.com/Brionjv/Tomodachi-Life-Save-Editor/files/2684082/savedataArc.txt)

**Comment by Brionjv** [comment]
What Mii did you edit ?

**Comment by Zeezers** [comment]
The 1st and 3rd miis
