### ISSUE TITLE
An error has occurred 

### ISSUE THREAD

**Issue by blanketkun** [Brionjv/Tomodachi-Life-Save-Editor#23]
"When writing editing of items, please report" This happens whenever I try to unlock all of my items and or unlock by numbers. I'm using 11.9 and the JKSV save editor, Is there anything I should be reading or am just not using common sense?

**Comment by Brionjv** [comment]
Are you opened a save file before try to unlock all of your items ?

**Comment by yumemomo** [comment]
foods, clothes, hats and treasures just don't work. They are not added in game. I tried like 5 times. But the money and miis works fine..
