### ISSUE TITLE
Crash when adding hats or items

### ISSUE THREAD

**Issue by ChildishGiant** [Brionjv/Tomodachi-Life-Save-Editor#26]
On the items part of this app, my game will crash whenever I try to add items or hats but not food or clothes.

I may be using it wrong though. How does the item adding system work and what do the two ticks on the side of the items mean?

**Comment by Brionjv** [comment]
If you check left, items will be set as available (available in store only, not in your inventory), check right to set as not available (delete all items in inventory and in stores).
To have items in inventory, set a number between 0 and 99 in middle
I will update items edit features on next update

**Comment by ChildishGiant** [comment]
It works with items but regardless of whether I put in 1 as the number of items I receive it will crash my game so I’m not sure what the problem is. I have tried only clicking streetpass/spotpass and only clicking set as available but they didn’t turn up in the shop

**Comment by Brionjv** [comment]
ok thanks, I'll rewrite all "items edit" features

**Comment by ChildishGiant** [comment]
I’m sorry! Re-reading that, there was a typo. I tried again with your advice, and adding 90 of each item/gift that you’d usually get from miis worked like a dream. Thank you! 

It’s just, the hats didn’t. I know the max number is 10 via researching it, but regardless of if I put the total as 1 for the hats or only ticked Streetpass, my game would say the file was corrupted. Also, ticking the ‘set as available’ option did not cause them to appear in store! 

Am I doing something wrong? Thanks for your help!

**Comment by Brionjv** [comment]
I don't know what happened, last version work for me. I rewrite all things in the editor. It's will probably fix with version 4.0.0
