### ISSUE TITLE
Editing Mii Relationship Corrupts The Whole Game

### ISSUE THREAD

**Issue by AuroraLaurailis** [Brionjv/Tomodachi-Life-Save-Editor#35]
I edited 2 of my mii's relationship and now when I try to add or edit a mii in game I can't save my game, i get the "Your game is corrupted please hit the home key to close the game" error.

**Comment by Brionjv** [comment]
make sure Mii not registered not have relationship.
If for example you don't have a Mii in "Mii 86" place and he have relationships, your save file will be corrupt. To fix that you need to set all relationship of this Mii on "Unknow"

**Comment by AuroraLaurailis** [comment]
The set all feature isn't working for some reason, but that is the issue, i'll just have to do it manually for now

**Comment by Brionjv** [comment]
Yes, set all relationship feature is lock because you don't have 100 Miis. It's to fix issue when set all relationship is used when you don't have 100 Miis

**Comment by AuroraLaurailis** [comment]
Fixed now! ^_^
