### ISSUE TITLE
Can't Edit ANYTHING, Error When Loading

### ISSUE THREAD

**Issue by PolarPeridot** [Brionjv/Tomodachi-Life-Save-Editor#36]
[savedataArc.txt](https://github.com/Brionjv/Tomodachi-Life-Save-Editor/files/3614430/savedataArc.txt)

So whenever I try to load my file, I immediately am bombarded with all kinds of errors. My region is USA and I'm using the latest version of the game, but nothing is working.

**Comment by Brionjv** [comment]
your save file is not corrupted when you load Tomodachi Life ?

**Comment by PolarPeridot** [comment]
No, it's not corrupted, and I extracted with Checkpoint.

**Comment by Brionjv** [comment]
There are something wrong with Checkpoint

This is a normal save file : 
![normal savefile](https://user-images.githubusercontent.com/22226393/64964746-f39a0a80-d89b-11e9-9bdb-5ea1015e35c1.png)

This is your save file : 
![wrong savefile](https://user-images.githubusercontent.com/22226393/64964747-f39a0a80-d89b-11e9-9b1a-8390b770cc4a.png)

I try to restore it and save is corrupted (with JK's save manager).

**Comment by PolarPeridot** [comment]
Hmm, OK. I'll see what I can do.

**Comment by PolarPeridot** [comment]
[savedataArc.txt](https://github.com/Brionjv/Tomodachi-Life-Save-Editor/files/3621344/savedataArc.txt)

Here's my save extracted with JKSM

**Comment by PolarPeridot** [comment]
Looks like it was a Checkpoint error. Using JKSM solved it. Weird, this is the only game that has issue with it. Oh well. Thanks for the tip!
