### ISSUE TITLE
What Key Is For The  Should I Have Child With (Mii)

### ISSUE THREAD

**Issue by JayTheGuy** [Brionjv/Tomodachi-Life-Save-Editor#41]
Im Using Tomodachi-Life-Save-Editor.4.0.0.Theta And Im Trying To Figure Out What The Key/Code Is For Should I Have I Child With (Mii) I Know Its Something Like 15E But I Dont Know What The Key Is For It. {The Key IS For The Interaction Pattern}

**Comment by Brionjv** [comment]
You can use last version, you can use a beta list
