### ISSUE TITLE
Mii Relationship Listed as "Unknown" when raising a child?

### ISSUE THREAD

**Issue by sagecappelwest** [Brionjv/Tomodachi-Life-Save-Editor#42]
I've noticed this when I try to edit relationship status of Miis when they're at any stage of having or raising a baby. I haven't noticed a false "Unknown" status in any other instance. I thought this would be worth looking into.

**Comment by Brionjv** [comment]
I check that, relationships shouldn't change.

**Comment by Brionjv** [comment]
fixed see ex-version
