### ISSUE TITLE
"set to available" or "set to unavailable" 

### ISSUE THREAD

**Issue by renamancy** [Brionjv/Tomodachi-Life-Save-Editor#46]
hi, i'm kinda just confused on how the controls work. I had assumed that "set to available" meant that said item would be available in-store for me to buy, but rather, all my stock items except for default are gone. 

i also tried to cheat in more travel tickets but those disappeared completely, am I just misunderstanding this? can i get a little insight on how EXACTLY to get stuff in my stores and increase inventory for certain things?

**Comment by Brionjv** [comment]
Hi,
Set as available feature set all items available in shop and delete your inventory
