### ISSUE TITLE
Divorcing Miis/Changing married mii relationships = corruption

### ISSUE THREAD

**Issue by SkyCrafterYT** [Brionjv/Tomodachi-Life-Save-Editor#47]
When you try to force Miis to divorce each other or change a married mii's relationship (even making sure to remove them from their house using the editor)- it seems to always corrupt the save. It either will boot up and say "Save corrupted, deleting and recreating" or "Creating save file".

If this isn't a bug and I'm just making a mistake... I would love for some help here! It looks like a bug though. :\

**Comment by SkyCrafterYT** [comment]
Update: I'm having trouble being able to edit relationships at all without it booting up in game with "Creating save file!"

Also: I forgot to mention when it says "Creating save file!" that it's a soft-lock.

**Comment by SkyCrafterYT** [comment]
Update 2: Going back to https://github.com/Brionjv/Tomodachi-Life-Save-Editor/releases/tag/4.0.0.k version allows me to change relationships just fine!

**Comment by Brionjv** [comment]
If you force Miis to divorce make sure you edit Mii house too or save file will be corrupted.

**Comment by SkyCrafterYT** [comment]
Brion, I mentioned I was also changing the house they were in to "House 1/None" for married miis! I also mentioned in an update that I would try to change any relationships (married **_or not_**) and it would corrupt the files still.

**Comment by Brionjv** [comment]
'll try to find where something goes wrong

**Comment by SkyCrafterYT** [comment]
https://github.com/Brionjv/Tomodachi-Life-Save-Editor/releases/tag/4.0.0.k did fix my problem relationship changes corrupting the game file, but married miis still would corrupt the game files even when you changed their house.

**Comment by SkyCrafterYT** [comment]
Update: After 23 days of not playing Tomodachi Life at all, the problem seems to have fixed itself. I'll let you know if it comes back up! :D
