### ISSUE TITLE
Adding Interactions = Corruption

### ISSUE THREAD

**Issue by YeestonCrack** [Brionjv/Tomodachi-Life-Save-Editor#48]
Hi! I was using the editor and added a interactions to one of my miis. Upon loading the game, my save file got corrupted. Ive tried to see whats the problem, use older versions of the editor, but nothing is working. Can you help me?

**Comment by Brionjv** [comment]
Make sure you are respected all conditions or save file can be corrupted. Last version give more informations about interactions. If you want more help tell me what did you do in the editor

**Comment by YeestonCrack** [comment]
Never mind i solved the problem! Mii#2 interaction pattern was all letters instead of a number.
