### ISSUE TITLE
Hats and special food causing data save corruption

### ISSUE THREAD

**Issue by ashbash23** [Brionjv/Tomodachi-Life-Save-Editor#50]
I don't know if I am the only one experiencing this but all the other items except the special food and hats work. Once I load up my game after adding the hats it causes my data save files to become corrupt. Hopefully this issue can be fixed in a new updated, because I want to see and have all the hats in my game.

**Comment by NetworkG** [comment]
You're not the only one I have the same issue

**Comment by Brionjv** [comment]
Last version should fix that, if you use last version tell me

**Comment by NetworkG** [comment]
Ok gonna try it

sob., 8 sie 2020, 17:19 użytkownik Brionjv <notifications@github.com>
napisał:
