### ISSUE TITLE
Changing a miis relationship to dating=corruption + more

### ISSUE THREAD

**Issue by areasell** [Brionjv/Tomodachi-Life-Save-Editor#52]
So my tomodachi life luck has not been doing well, this time for non-stupid reasons. The lock is off on my SD card this time haha.

Whenever I change a miis relationship with another mii of the opposite sex's relationship to dating/married, the save gets corrupted. This also happens when I change two or more miis to be friends with all of the islanders and when I choose ANYTHING in the questions category (I'm hungry, I want to propose to a mii, those types). This used to work perfectly last month so i'm quite puzzled as to why it would not work now?

**Comment by Brionjv** [comment]
did you check your target too ?

**Comment by ChibiTk** [comment]
Yes I made sure the targets relationship status matched and only had one special someone

**Comment by Brionjv** [comment]
can you send your save file, please ?
