### ISSUE TITLE
Trying to edit a Mii causes crash of application

### ISSUE THREAD

**Issue by 3DSWIIU** [Brionjv/Tomodachi-Life-Save-Editor#54]
Everytime, i want to edit a Mii the program crashes! IDK if it's bc 100 Miis but if it's bc that, this need to be fixed!

**Comment by Brionjv** [comment]
if you edit in a SD card check if is not locked

**Comment by 3DSWIIU** [comment]
It's not locked. Otherwise the 3ds would not be able to start! (CFW only)

**Comment by MaxACartwright** [comment]
I have the same problem!

**Comment by Brionjv** [comment]
should be fixed now
