### ISSUE TITLE
Changed Mii relationship level is not saving

### ISSUE THREAD

**Issue by Szprinktrap** [Brionjv/Tomodachi-Life-Save-Editor#55]
When i go to my Mii list and change relationship level (for example from "Slightly unhappy" to "One in a million"), click Save, then switch to different Mii and switch back, it reverts to original level.

PS. Sorry if my English is bad, I'm Polish.

**Comment by Brionjv** [comment]
You can try to save to times

**Comment by FishyTM** [comment]
So, I found out that the miis relationship status can be changed but only miis on the first page are able to be changed. So like if I want to edit a mii that's on the 3rd page, I can edit their thoughts/relationship with someone on the first page. But you can't edit someone's thoughts about someone past the 1st page.

**Comment by Brionjv** [comment]
I'll try check that, thanks
