### ISSUE TITLE
Infinite Baby's

### ISSUE THREAD

**Issue by NaIyx** [Brionjv/Tomodachi-Life-Save-Editor#57]
One of my couples are having non stop babies.

**Comment by NaIyx** [comment]
I can't change it to 'nothing' because then my save gets corrupted.

**Comment by Brionjv** [comment]
can you send your save file, please ?

**Comment by TRASHCANUWU** [comment]
> I can't change it to 'nothing' because then my save gets corrupted.

Hey, commenter, could you find a way to fix this?

**Comment by Brionjv** [comment]
If you still have troubles with new update open an other issue
