### ISSUE TITLE
Infinemite babies

### ISSUE THREAD

**Issue by TRASHCANUWU** [Brionjv/Tomodachi-Life-Save-Editor#60]
I know someone already posted about this but I'm having the same problem over here.
My mii's won't stop calling me to tell me they had babies, and it's getting annoying :(

**Comment by Brionjv** [comment]
set all of your interactions to none

**Comment by TRASHCANUWU** [comment]
I already tried that, it corrupts my save file

**Comment by Brionjv** [comment]
can you sent your save file, please ? I'll check what's goes wrong
