### ISSUE TITLE
Corrupt when changing a Mii’s Relationship / Relationship Status

### ISSUE THREAD

**Issue by avarich** [Brionjv/Tomodachi-Life-Save-Editor#63]
I have been trying to make two Mii's best friends, but every time I try to do so it says the file is corrupt. Neither of them already had best friends, so I don't know what the issue is. 

Same thing with changing a Mii's relationship status. I wanted to make two people go from "Getting Along Okay" and "Not Getting Along" to "Great Pals", and every time I try to do so the file is corrupt. 

I've used this save editor before when editing favorite foods, and it worked fine.

**Comment by Brionjv** [comment]
I don't know too, I need more informations to help you

**Comment by purpelpower** [comment]
oke i have the same so i set mii 1=donkey to house 2 and then when i load the game it says its creating a new save

**Comment by purpelpower** [comment]
issue corrected let the mii's manually go to their homes
