### ISSUE TITLE
save will not load in editor

### ISSUE THREAD

**Issue by 2cupsoforangejuice** [Brionjv/Tomodachi-Life-Save-Editor#65]
this is the first time ive used the save editor in a while, probably a year, and when i used it then it worked
i had updated to the newest version and tried to edit my save (digital usa), but when i open it nothing loads, and no error messages either; its just blank. i even when i went back to the old version i had, nada. then i switched from checkpoint to JKSM, didnt help. not sure whats happened to my save or whatever to cause this
![image](https://user-images.githubusercontent.com/77173265/104063137-89078f00-51b0-11eb-9d34-e1995133f967.png)

**Comment by Brionjv** [comment]
weird, can you send your save file to see what goes wrong ?

**Comment by 2cupsoforangejuice** [comment]
[savedataArc.txt](https://github.com/Brionjv/Tomodachi-Life-Save-Editor/files/5791653/savedataArc.txt)

**Comment by Brionjv** [comment]
your save file is loaded successfully with latest version
![saveload](https://user-images.githubusercontent.com/22226393/104130793-14c91900-5373-11eb-95d9-c79a808381b0.png)

**Comment by 2cupsoforangejuice** [comment]
weird, i'll try again
