### ISSUE TITLE
JP File Save not unlocking certain hats/colors

### ISSUE THREAD

**Issue by GizzyVec** [Brionjv/Tomodachi-Life-Save-Editor#66]
![image](https://user-images.githubusercontent.com/54750846/104081340-fb519100-51fb-11eb-84e2-f06baaf5e82a.png) 
![image](https://user-images.githubusercontent.com/54750846/104081371-263be500-51fc-11eb-9330-8e692f0ca8d7.png)
With using the save editor, and the ability to try to unlock all hats, in the Japanese version of the game, it unlocks everything, including clothes, food, and everything else, and most hats, except these specific ones. I've tried using another save file, deleting the items and using the save editor again, and to no success.
Edit: The hat on the bottom seems to be known as the "Work Cap".

**Comment by Brionjv** [comment]
Hi, thanks I'll try to fix that
