### ISSUE TITLE
Same sex, is same than corruption in spouse relationships

### ISSUE THREAD

**Issue by miguelga35** [Brionjv/Tomodachi-Life-Save-Editor#68]
I have this question, because my save file got corrupted and I erased it, I have this error more than 1 time
And the game don't start unless you start new savedata
My "gay and lesbian" relationships is the problem here
And I tested too with babies and it's enabled with normal relation ships and I changed the interaction pattern to grow up the baby, I select one of two options
And the baby don't go back into the island and he disappeared  but their family album is always here and I can't erased it
The smiilar with same sex in a home
(Note: When is lover that's works perfectly)

**Comment by Brionjv** [comment]
having same sex relationships can cause somes issues, save editor can't fix that. You can try with 
tomodachi Life version 1.0
1.1 version fix same sex relationships

**Comment by miguelga35** [comment]
Well, you mean Tomodachi Life 1.0 version without update right?

**Comment by miguelga35** [comment]
I have installed it and i will do the test again

**Comment by Brionjv** [comment]
> Well, you mean Tomodachi Life 1.0 version without update right?

yes

**Comment by miguelga35** [comment]
The same result, it crashes with the first house with same sex relationships in EUR version with a cia

**Comment by Brionjv** [comment]
I don't know how to fix that sorry

**Comment by miguelga35** [comment]
> I don't know how to fix that sorry

Ok, don't worry, thanks anyways!
