### ISSUE TITLE
save editor shows nothing when opening file

### ISSUE THREAD

**Issue by expiredgum** [Brionjv/Tomodachi-Life-Save-Editor#70]
whenever i open the save editor and load my file, nothing changes, as if i never opened a file, it still asks me for my region, but nothing. i tried using issue 36 and used both checkpoint and jk save manager but nothing

**Comment by Brionjv** [comment]
you need to choose your save file version, if you don't have any error message you can edit your save file as you want. You can have more informations about features in save editor, just check "show advance help" in settings

**Comment by expiredgum** [comment]
> you need to choose your save file version, if you don't have any error message you can edit your save file as you want. You can have more informations about features in save editor, just check "show advance help" in settings
i did that but when i opened my savedataarc.txt file, nothing loads, i wait and wait but nothing.

**Comment by Brionjv** [comment]
try to paste your save file in other location and retry

**Comment by ri0tgrrrl** [comment]
I still can’t sort this out it’s driving me mad lol. I keep getting error messages pop up “unhandled exception has occurred in your application”. Idk if I’m doing anything wrong with saving on checkpoint or jksm or what
