### ISSUE TITLE
Changed Mii Relationship, She's Stuck in Someone's House?

### ISSUE THREAD

**Issue by NicoColeco** [Brionjv/Tomodachi-Life-Save-Editor#75]
I went and changed my Mii's relationships. She went from "married" from one Mii to "in a relationship" with another Mii. Now whenever I check her apartment, it says that she is visiting "??? and ???'s house". Pressing the "locate" button takes me to the first house on the list, but no one is home. She can still be called back, but once I leave her apartment, she's no longer there, and returns to this status.
I went through her relationships and made sure there were no duplicate statuses, as having more than one "sweetheart" or "married" status corrupts the game. She remains at "good friends/ex-spouse" status to her previous husband Mii. Should I try changing her previous spouse to just a friend? I've never seen this glitch happen before. Thanks for your time.

EDIT: Tried changing previous spouse to "just friends." She also has a Mii listed as her ex-boyfriend. No matter what relationship changes I make, it seems that something is off. Help...?

**Comment by Brionjv** [comment]
When you set 2 Mii married you need to choose Mii house, set same number for each couple member

**Comment by toxicpoizon** [comment]
how do i do that? i chose mii house in island config, but i dont see anything about editing mii home numbers
