### ISSUE TITLE
it infinitly loads and says creating save data when i make 1 person love another person

### ISSUE THREAD

**Issue by bigboie22** [Brionjv/Tomodachi-Life-Save-Editor#76]

**Comment by Brionjv** [comment]
You need to respect interaction condition

**Comment by LolHarambe33** [comment]
> You need to respect interaction condition

Could you write some sort of manual or guide that goes more in-depth? I'm not sure what "interaction condition" means.

**Comment by Brionjv** [comment]
if you used an interaction you need to repect this (for exemple): 
![interaction](https://user-images.githubusercontent.com/22226393/123309135-d42a1a00-d524-11eb-8a44-40a47e0cacc8.png)
