### ISSUE TITLE
Game says save is corrupted after editing relationships

### ISSUE THREAD

**Issue by circuit-man1** [Brionjv/Tomodachi-Life-Save-Editor#77]
Game says save is corrupted after editing relationships, and I even made sure the mii only has 1 "sweetheart"

**Comment by Pixelizado** [comment]
Me too, and it's not just sweetheart, it's also with any relationship .....

**Comment by circuit-man1** [comment]
ok i'm glad to know its not only me. do you use an emulator? if you do, it might be the problem because I use one.. though idk how that could cause any problems
