### ISSUE TITLE
Save data is corrupted and will be deleted (after edit a mii relationship,musics learned, problem for solve)

### ISSUE THREAD

**Issue by Pixelizado** [Brionjv/Tomodachi-Life-Save-Editor#78]
Hi! I have a problem. every time i edit something in any mii, the corrupted save game, what can i do to get it working properly?
[savedataArc.txt](https://github.com/Brionjv/Tomodachi-Life-Save-Editor/files/6524806/savedataArc.txt)

**Comment by Brionjv** [comment]
What feature did you used ?

**Comment by Gavin123-code** [comment]
same thing i edited mii relationship

**Comment by Gavin123-code** [comment]
after editing save data corrupted

**Comment by Brionjv** [comment]
check if your Mii don't have more than one sweetheart or best friend

**Comment by Pixelizado** [comment]
no, i didn't edit the best friend and sweetheart relationships, i just put
in more friendships and edited the sounds the mii had

Em qui, 24 de jun de 2021 2:42 PM, Brionjv ***@***.***>
escreveu:

**Comment by Brionjv** [comment]
What the name of your edited Mii ?

**Comment by Pixelizado** [comment]
Igor
Stela
Pri
Jhonny
Lara
Gui

the six Miis I edited

Em qua, 7 de jul de 2021 12:50 PM, Brionjv ***@***.***>
escreveu:

**Comment by Brionjv** [comment]
All relationships seem to be good. I'll try to reset some things to see what goes wrong
