### ISSUE TITLE
Unable to edit mii relationships/problems

### ISSUE THREAD

**Issue by terminallysoryu** [Brionjv/Tomodachi-Life-Save-Editor#80]
When I try to edit a mii's relationship with another mii or assign it a problem (ex. wants to eat), it doesn't carry over to the game. I make sure to save it before closing, but it just doesn't show up in-game.

**Comment by terminallysoryu** [comment]
Still need help w this

**Comment by CassieWillKnifeU** [comment]
I have the same problem.

**Comment by Brionjv** [comment]
You need to have a recent save file (for exemple  : save 2min ago) interaction use last save date to show interactions
