### ISSUE TITLE
Invalid Save File Help?

### ISSUE THREAD

**Issue by coldpillow2** [Brionjv/Tomodachi-Life-Save-Editor#87]
I'm having an issue with even getting my save file to import correctly.

I'm using the latest versions of the save editor, Checkpoint and JKSM, and when I backup the save through either Checkpoint or JKSM it's always named as SaveDataArc.txt. However, when I try to open it through the save manager, it tells me it's an 'invalid save file'. I don't use any special characters as the file name or anything like that. When I open another person's save file everything seems fine and the save editor prompts me to choose between the EUR or USA version of the game, as it's seemingly supposed to.

Since I'm using a hacked version of the game (USA), could this be contributing to my problem? I have a 'legit' CIA via hShop too.

**Comment by Brionjv** [comment]
Can you send you save file too what goes wrong ?

**Comment by coldpillow2** [comment]
Thanks, I figured that was why.
