### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Myselforsomethingsimilar** [Brionjv/Tomodachi-Life-Save-Editor#91]
[savedataArc.txt](https://github.com/Brionjv/Tomodachi-Life-Save-Editor/files/7185407/savedataArc.txt)

So my file corrupted after editing it and I don't know the reason, what's so janky about this file?
I tried editing some relationships, but I do not know if the corruption is related to that.

**Comment by Myselforsomethingsimilar** [comment]
Also, the latest save I've done was yesterday at 7:30 pm something

**Comment by TroyTT4** [comment]
it seems that changing relationships or relationship statuses will always cause the save data to be corrupted. I hope this gets fixed soon

**Comment by Brionjv** [comment]
I work on a update, but I no have time for now.
