### ISSUE TITLE
Date changed causing interactions to break

### ISSUE THREAD

**Issue by Rapfamous** [Brionjv/Tomodachi-Life-Save-Editor#92]
When I make somebody say something like
(e.g I'm in love with mii, I've got to tell them"
it says "the time of day has changed blah blah blah"
and they dont have the interaction anymore, please fix it

**Comment by Brionjv** [comment]
To work properly you need to used a recent save file. Save in the game and extract your save

**Comment by Rapfamous** [comment]
> To work properly you need to used a recent save file. Save in the game and extract your save

I did use the most recent save file, but it says the date changed, please fix it

**Comment by Brionjv** [comment]
load you game, save and extract you save file

**Comment by Rapfamous** [comment]
> load you game, save and extract you save file

Il me vient à l’esprit que vous connaissez Français plus que l’anglais, alors je vais dis-le ici.  quand je modifie le fichier de sauvegarde il finit par mal se comporter puis le jour change et quand je modifie les interactions ça le rend différent de ce que je mets...

**Comment by Rapfamous** [comment]
> > > load you game, save and extract you save file
> > 
> > 
> > Il me vient à l’esprit que vous connaissez Français plus que l’anglais, alors je vais dis-le ici. quand je modifie le fichier de sauvegarde il finit par mal se comporter puis le jour change et quand je modifie les interactions ça le rend différent de ce que je mets...
> 
> Les interactions utilisent la date où tu as sauvegardé, si tu as le message que la date a changé, tu dois lancer ton jeu, passer le message puis sauvegarder. Ensuite extraire cette même sauvegarde. Si ça ne fonctionne pas, envoi moi ton fichier de sauvegarde pour voir ce que je peux faire
[savedataArc.txt](https://github.com/Brionjv/Tomodachi-Life-Save-Editor/files/7255492/savedataArc.txt)

**Comment by Rapfamous** [comment]
> > > load you game, save and extract you save file
> > 
> > 
> > Il me vient à l’esprit que vous connaissez Français plus que l’anglais, alors je vais dis-le ici. quand je modifie le fichier de sauvegarde il finit par mal se comporter puis le jour change et quand je modifie les interactions ça le rend différent de ce que je mets...
> 
> Les interactions utilisent la date où tu as sauvegardé, si tu as le message que la date a changé, tu dois lancer ton jeu, passer le message puis sauvegarder. Ensuite extraire cette même sauvegarde. Si ça ne fonctionne pas, envoi moi ton fichier de sauvegarde pour voir ce que je peux faire

excuse me. I sent the save data file are u working on it?

**Comment by Rapfamous** [comment]
> your save is corrupted, can you sent an other ? If you used save editor, you have copies in backup folder in save editor location

I have sent it
