### ISSUE TITLE
"Save data is corrupted" errors aren't gone

### ISSUE THREAD

**Issue by TroyTT4** [Brionjv/Tomodachi-Life-Save-Editor#96]
the issue is exactly what the title says. I tried the new version and the game still said that the save data was corrupted afterwards.

since I'm sure this will help solve this issue, here's what I changed with the editor:

I edited the relationship level of two miis who are best friends up from "kind of getting along" to "best friends forever" so they wouldn't stop being best friends.

Mii A and mii S were just regular friends, and mii S and mii P were best friends. I edited S and A to be best friends, and S and P to be regular friends.

**Comment by Brionjv** [comment]
I will do some test to see what goes wrong, when you edit a relationship if they are more than one special someone or best friend, this relationship should be selected in red to show an error (in your case if Mii A have other best friend than Mii S, save file will be corrupt).
You can select Mii A, Mii S, and Mii P and check their friend list to see if they are relationships in red

**Comment by TroyTT4** [comment]
when I tried editing this it was on version 4.0.0.
I tried again using EX 1.0.1 and it worked.
I don't know why it works in EX and not in 4, but at least it works in one of them

**Comment by Brionjv** [comment]
in version 4.0.0 relationships are not saved, to use relationships features you need to use EX version. 
If your problem is solved you can close this issue
