### ISSUE TITLE
Save button is missing from latest version and also EX version is broken???

### ISSUE THREAD

**Issue by BlueDragonKaiser** [Brionjv/Tomodachi-Life-Save-Editor#97]
Hi I was really excited to use this program but I'm running into too many issues. I'm not trying to edit relationships anymore but rather I'm trying to edit my money and unlock shops faster. Problem is the "save" button is missing from the latest release. When I open my save file the Open button doesn't change to Save. So there's no way to save any changes.

As for the EX version it only opens Miis and nothing else.

**Comment by Brionjv** [comment]
Hi, I do something  wrong in 4.0.0 version sorry for that, in version EX you can only edit relationships

**Comment by TroyTT4** [comment]
the reason there isn't a save button is because it auto-saves changes you make now

**Comment by Brionjv** [comment]
> the reason there isn't a save button is because it auto-saves changes you make now

no save editor don't have auto-saves features, it fixed now

**Comment by TroyTT4** [comment]
> no save editor don't have auto-saves features, it fixed now

oh I thought it auto saved because when I loaded the save that I thought I had edited the game gave me the "corrupted data" error. weird considering that the save hadn't actually been changed. I guess this changes things about the issue I posted a week ago.

**Comment by Brionjv** [comment]
no problem, you can test with EX version if you want edit relationships
